// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransOil.DataContext;

#nullable disable

namespace TransOil.DataContext.Migrations
{
    [DbContext(typeof(TransOilContext))]
    [Migration("20240711130815_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MeasurementDeviceMeasurementPoint", b =>
                {
                    b.Property<int>("DevicesDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementPointsMeasurementPointId")
                        .HasColumnType("int");

                    b.HasKey("DevicesDeviceId", "MeasurementPointsMeasurementPointId");

                    b.HasIndex("MeasurementPointsMeasurementPointId");

                    b.ToTable("MeasurementDeviceMeasurementPoint");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.CompanyBase", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(128)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies", (string)null);

                    b.HasDiscriminator().HasValue("CompanyBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.CounterBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("varchar(34)");

                    b.Property<int>("MeasurementPointId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("VerifyDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Counters");

                    b.HasDiscriminator().HasValue("CounterBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.ElectricitySupplyPoint", b =>
                {
                    b.Property<int>("SupplyPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SupplyPointId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<double>("MaxVoltage")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("SupplyPointId");

                    b.HasIndex("CustomerId");

                    b.ToTable("SupplyPoints");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.Measurement", b =>
                {
                    b.Property<int>("MeasurementDeviceId")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementPointId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2024, 7, 11, 16, 8, 15, 29, DateTimeKind.Local).AddTicks(9853));

                    b.HasKey("MeasurementDeviceId", "MeasurementPointId", "Date");

                    b.HasIndex("MeasurementPointId");

                    b.ToTable("Measurements");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.MeasurementDevice", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DeviceId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("DeviceId");

                    b.ToTable("MeasurementDevices");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.MeasurementPoint", b =>
                {
                    b.Property<int>("MeasurementPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MeasurementPointId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("MeasurementPointId");

                    b.HasIndex("CustomerId");

                    b.ToTable("MeasurementPoints");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.ChildCompany", b =>
                {
                    b.HasBaseType("TransOil.DataContext.EntityModels.CompanyBase");

                    b.Property<int>("ParentCompanyId")
                        .HasColumnType("int");

                    b.ToTable("Companies", (string)null);

                    b.HasDiscriminator().HasValue("ChildCompany");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.Company", b =>
                {
                    b.HasBaseType("TransOil.DataContext.EntityModels.CompanyBase");

                    b.ToTable("Companies", (string)null);

                    b.HasDiscriminator().HasValue("Company");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.ElectricEnergyCounter", b =>
                {
                    b.HasBaseType("TransOil.DataContext.EntityModels.CounterBase");

                    b.HasIndex("MeasurementPointId")
                        .IsUnique();

                    b.ToTable("Counters", (string)null);

                    b.HasDiscriminator().HasValue("ElectricEnergyCounter");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.TransformerCounterBase", b =>
                {
                    b.HasBaseType("TransOil.DataContext.EntityModels.CounterBase");

                    b.Property<double>("TranformerRatio")
                        .HasColumnType("double");

                    b.HasDiscriminator().HasValue("TransformerCounterBase");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.CurrentTransformer", b =>
                {
                    b.HasBaseType("TransOil.DataContext.EntityModels.TransformerCounterBase");

                    b.HasIndex("MeasurementPointId")
                        .IsUnique();

                    b.ToTable("Counters", (string)null);

                    b.HasDiscriminator().HasValue("CurrentTransformer");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.VoltageTransformer", b =>
                {
                    b.HasBaseType("TransOil.DataContext.EntityModels.TransformerCounterBase");

                    b.HasIndex("MeasurementPointId")
                        .IsUnique();

                    b.ToTable("Counters", (string)null);

                    b.HasDiscriminator().HasValue("VoltageTransformer");
                });

            modelBuilder.Entity("MeasurementDeviceMeasurementPoint", b =>
                {
                    b.HasOne("TransOil.DataContext.EntityModels.MeasurementDevice", null)
                        .WithMany()
                        .HasForeignKey("DevicesDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransOil.DataContext.EntityModels.MeasurementPoint", null)
                        .WithMany()
                        .HasForeignKey("MeasurementPointsMeasurementPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.Customer", b =>
                {
                    b.HasOne("TransOil.DataContext.EntityModels.ChildCompany", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.ElectricitySupplyPoint", b =>
                {
                    b.HasOne("TransOil.DataContext.EntityModels.Customer", "Customer")
                        .WithMany("Supplies")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.Measurement", b =>
                {
                    b.HasOne("TransOil.DataContext.EntityModels.MeasurementDevice", "MeasurementDevice")
                        .WithMany("Measurements")
                        .HasForeignKey("MeasurementDeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TransOil.DataContext.EntityModels.MeasurementPoint", "MeasurementPoint")
                        .WithMany("Measurements")
                        .HasForeignKey("MeasurementPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementDevice");

                    b.Navigation("MeasurementPoint");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.MeasurementPoint", b =>
                {
                    b.HasOne("TransOil.DataContext.EntityModels.Customer", "Customer")
                        .WithMany("Measurments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.ChildCompany", b =>
                {
                    b.HasOne("TransOil.DataContext.EntityModels.Company", "Company")
                        .WithMany("ChildCompanies")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.ElectricEnergyCounter", b =>
                {
                    b.HasOne("TransOil.DataContext.EntityModels.MeasurementPoint", "MeasurementPoint")
                        .WithOne("ElectricityCounter")
                        .HasForeignKey("TransOil.DataContext.EntityModels.ElectricEnergyCounter", "MeasurementPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementPoint");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.CurrentTransformer", b =>
                {
                    b.HasOne("TransOil.DataContext.EntityModels.MeasurementPoint", "MeasurementPoint")
                        .WithOne("CurrentTransformer")
                        .HasForeignKey("TransOil.DataContext.EntityModels.CurrentTransformer", "MeasurementPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementPoint");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.VoltageTransformer", b =>
                {
                    b.HasOne("TransOil.DataContext.EntityModels.MeasurementPoint", "MeasurementPoint")
                        .WithOne("VoltageTransformer")
                        .HasForeignKey("TransOil.DataContext.EntityModels.VoltageTransformer", "MeasurementPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MeasurementPoint");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.Customer", b =>
                {
                    b.Navigation("Measurments");

                    b.Navigation("Supplies");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.MeasurementDevice", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.MeasurementPoint", b =>
                {
                    b.Navigation("CurrentTransformer")
                        .IsRequired();

                    b.Navigation("ElectricityCounter")
                        .IsRequired();

                    b.Navigation("Measurements");

                    b.Navigation("VoltageTransformer")
                        .IsRequired();
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.ChildCompany", b =>
                {
                    b.Navigation("Customers");
                });

            modelBuilder.Entity("TransOil.DataContext.EntityModels.Company", b =>
                {
                    b.Navigation("ChildCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
